const questions = [
    "Walk me through the 3 financial statements.",
    "Can you give examples of major line items on each of the financial statements?",
    "How do the 3 statements link together?",
    "If I were stranded on a desert island, only had 1 statement and I wanted to review the overall health of a company – which statement would I use and why?",
    "Let’s say I could only look at 2 statements to assess a company’s prospects – which 2 would I use and why?",
    "Let’s say I have a new, unknown item that belongs on the Balance Sheet. How can I tell whether it should be an Asset or a Liability?",
    "How can you tell whether or not an expense should appear on the Income Statement?",
    "Let’s say that you have a non-cash expense (Depreciation or Amortization, for example) on the Income Statement. Why do you add back the entire expense on the Cash Flow Statement?    ",
    "How do you decide when to capitalize rather than expense a purchase?   ",
    "If Depreciation is a non-cash expense, why does it affect the cash balance?    ",
    "Where does Depreciation usually appear on the Income Statement?",
    "Why is the Income Statement not affected by Inventory purchases?",
    "Debt repayment shows up in Cash Flow from Financing on the Cash Flow Statement. Why don’t interest payments also show up there? They’re a financing activity!",
    "What’s the difference between Accounts Payable and Accrued Expenses?",
    "When would a company collect cash from a customer and not record it as revenue?",
    "If cash collected is not recorded as revenue, what happens to it?",
    "Wait a minute... Deferred Revenue reflects cash that we’ve already collected upfront for a product/service we haven’t delivered yet. Why is it a Liability? That’s great for us!",
    "Wait, so what’s the difference between Accounts Receivable and Deferred Revenue? They sound similar.",
    "How long does it usually take for a company to collect its Accounts Receivable balance?",
    "How are Prepaid Expenses (PE) and Accounts Payable (AP) different?    ",
];


const answers = [
    "The three major financial statements are the Income Statement, Balance Sheet, and Cash Flow Statement which provide information on a company's revenue, expenses, assets, liabilities, equity, and cash flow.",
    "The Income Statement shows revenue, expenses, and net income; the Balance Sheet shows assets, liabilities, and equity; and the Cash Flow Statement shows the sources and uses of cash from operating, investing, and financing activities.",
    "Net Income adds to Cash Flow, adjusted for Balance Sheet changes. Investing & financing activities yield the net change in cash; Assets = Liabilities + Equity.",
    "The Cash Flow Statement shows a company's actual cash generation, unlike the Income Statement which may be misleading, making it crucial for analysis.",
    "The Income Statement and Balance Sheet can be used to create the Cash Flow Statement, making them important financial statements for analysis.",
    "An Asset will result in additional cash or potential cash in the future – think about how Investments or Accounts Receivable will result in a direct cash increase, and how Goodwill or PP&E may result in an indirect cash increase in the future. A Liability will result in less cash or potential cash in the future – think about how Debt or Accounts Payable will result in a direct cash decrease, and how something like Deferred Revenue will result in an indirect cash decrease as you recognize additional taxes in the future from recognizing revenue. Ask what direction cash will move in as a result of this new item and that tells you whether it’s an Asset or Liability.",
    "Two conditions MUST be true for an expense to appear on the IS:1. It must correspond to something in the current period.2. It must be tax-deductible.Employee compensation and marketing spending, for example, satisfy bothconditions.Depreciation and Interest Expense also meet both conditions – Depreciation only represents the “loss in value” of PP&E (or to be more technically precise, the allocation of the investment in PP&E) in the current period you’re in.Repaying debt principal does not satisfy both of these conditions because it is not tax-deductible.Advanced Note: Technically, “tax-deductible” here means “deductible for book tax purposes” (i.e. only the tax number that appears on the company’s Income Statement)",
    "Because you want to reflect that you’ve saved on taxes with the non-cash expense.Let’s say you have a non-cash expense of $10 and a tax rate of 40%. Your Net Income decreases by $6 as a result... but then you add back the entire non-cash expense of $10 on the CFS so that your cash goes up by $4. That increase of $4 reflects the tax savings from the non-cash expense. If you just added back the after-tax expense of $6 you’d be saying, “This non-cash expense has no impact on our taxes or cash balance.",
    "If the purchase corresponds to an Asset with a useful life of over 1 year, it is capitalized (put on the Balance Sheet rather than shown as an expense on the Income Statement). Then it is Depreciated (tangible assets) or Amortized (intangible assets) over a certain number of years.Purchases like factories, equipment and land all last longer than a year and therefore show up on the Balance Sheet. Employee salaries and the cost of manufacturing products (COGS) only “last” for the current period and therefore show up on the Income Statement as normal expenses instead.Note that even if you’re paying for something like a multi-year lease for a building, you would not capitalize it unless you own the building and pay for the entire building in advance.",
    "Although Depreciation is a non-cash expense, it is tax-deductible. Therefore, an increase in Depreciation will reduce the amount of taxes you pay, which boosts your cash balance. The opposite happens if Depreciation decreases.",
    "It could be in a separate line item, or it could be embedded in Cost of Goods Sold or Operating Expenses – each company does it differently. Note that the end result for accounting questions is the same: Depreciation always reduces Pre-Tax Income.",
    "The expense of purchasing Inventory is only recorded on the Income Statement when the goods associated with it have been manufactured and sold – so if it’s just sitting in a warehouse, it does not count as Cost of Goods Sold (COGS) until the company manufactures it into a product and sells it.",
    "The difference is that interest payments correspond to the current period and are tax-deductible, so they have already appeared on the Income Statement. Since they are a true cash expense and already appeared on the IS, showing them on the CFS would be double-counting them and would be incorrect.Debt repayments are a true cash expense but they do not appear on the IS, so we need to adjust for them on the CFS.If something is a true cash expense and it has already appeared on the IS, it will never appear on the CFS unless we are re-classifying it – because you have already factored in its cash impact.",
    "Mechanically, they are the same: they’re Liabilities on the Balance Sheet used when you’ve recorded an Income Statement expense for a product/service you have received, but have not yet paid for in cash. They both affect the statements in the same way as well (see the model). The difference is that Accounts Payable is mostly for one-time expenses with invoices, such as paying for a law firm, whereas Accrued Expenses is for recurring expenses without invoices, such as employee wages, rent, and utilities.",
    "Typically this happens when the customer pays upfront, in cash, for months or years of a product/service, but the company hasn’t delivered it yet. Cases where you see this:1. Web-based subscription software.2. Cell phone carriers that sell annual contracts.3. Magazine publishers that sell subscriptions.You only record revenue when you actually deliver the products / services – so the company does not record cash collected as revenue right away.",
    "It goes into the Deferred Revenue balance on the Balance Sheet under Liabilities.Over time, as the services or products are delivered, the Deferred Revenue balance turns into real revenue on the Income Statement and the Deferred Revenue balance decreases.",
    "Remember the definitions of Assets and Liabilities: an Asset results in more future cash, and a Liability results in less future cash.Think about how Deferred Revenue works: not only is the burden on us to deliver the product/service in question, but we are also going to pay additional taxes and possibly recognize additional future expenses when we record it as real revenue.It’s counter-intuitive, but that is why Deferred Revenue is a liability: it implies additional future expenses.",
    "There are 2 main differences:1. Accounts Receivable has not yet been collected in cash from customers, whereas Deferred Revenue has been.2. Accounts Receivable is for a product/service the company has already delivered but hasn’t been paid for yet, whereas Deferred Revenue is for a product/service the company has not yet delivered.Accounts Receivable is an Asset because it implies additional future cash whereas Deferred Revenue is a Liability because it implies the opposite.",
    "Generally the Accounts Receivable Days are in the 30-60 day range, though it can be higher for companies selling higher-priced items and it might be lower for companies selling lower-priced items with cash payments only.    ",
    "It’s similar to the difference between Accounts Receivable and Deferred Revenue above:1. Prepaid Expenses have already been paid out in cash, but haven’t yet shown up on the Income Statement, whereas Accounts Payable haven’t been paid out in cash but have shown up on the IS.2. PE is for product/services that have not yet been delivered to the company, whereas AP is for products/services that have already been delivered.",
];

const questionAnswerPairs = questions.map((question, index) => ({
    question,
    answer: answers[index],
}));
